# These are supported funding model platforms

github: [Phu1237]
patreon: Phu1237
buy_me_a_coffee: Phu1237
thanks_dev: u/gh/phu1237
custom: ['https://www.paypal.me/Phu1237', 'https://me.momo.vn/Phu1237']
